In [21]:
#Combinig Data 
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_excel('C:/Users/ajayt/OneDrive/Desktop/DataSets/data/salesfunnel.xlsx')
df.columns

Index(['Account', 'Name', 'Rep', 'Manager', 'Product', 'Quantity', 'Price',
       'Status'],
      dtype='str')

In [7]:
df.head()

,Account,Name,Rep,Manager,Product,Quantity,Price,Status
0,714466,Trantow-Barrows,Craig Booker,Debra Henley,CPU,1,30000,presented
1,714466,Trantow-Barrows,Craig Booker,Debra Henley,Software,1,10000,presented
2,714466,Trantow-Barrows,Craig Booker,Debra Henley,Maintenance,2,5000,pending
3,737550,"Fritsch, Russel and Anderson",Craig Booker,Debra Henley,CPU,1,35000,declined
4,146832,Kiehn-Spinka,Daniel Hilton,Debra Henley,CPU,2,65000,won

In [8]:
df["Status"]=df["Status"].astype("category")
df["Status"].cat.set_categories(["won","pending","presented","declined"])
print(df.head())
df.dtypes
#df=df.drop_duplicate() # To remove Duplicate if any

   Account                          Name            Rep       Manager  \
0   714466               Trantow-Barrows   Craig Booker  Debra Henley
1   714466               Trantow-Barrows   Craig Booker  Debra Henley
2   714466               Trantow-Barrows   Craig Booker  Debra Henley
3   737550  Fritsch, Russel and Anderson   Craig Booker  Debra Henley
4   146832                  Kiehn-Spinka  Daniel Hilton  Debra Henley

       Product  Quantity  Price     Status
0          CPU         1  30000  presented
1     Software         1  10000  presented
2  Maintenance         2   5000    pending
3          CPU         1  35000   declined
4          CPU         2  65000        won

Account        int64
Name             str
Rep              str
Manager          str
Product          str
Quantity       int64
Price          int64
Status      category
dtype: object

In [11]:
pd.pivot_table(df,index=['Name'],values=["Quantity","Price"],aggfunc='mean')

                                 Price  Quantity
Name
Barton LLC                     35000.0  1.000000
Fritsch, Russel and Anderson   35000.0  1.000000
Herman LLC                     65000.0  2.000000
Jerde-Hilpert                   5000.0  2.000000
Kassulke, Ondricka and Metz     7000.0  3.000000
Keeling LLC                   100000.0  5.000000
Kiehn-Spinka                   65000.0  2.000000
Koepp Ltd                      35000.0  2.000000
Kulas Inc                      25000.0  1.500000
Purdy-Kunde                    30000.0  1.000000
Stokes LLC                      7500.0  1.000000
Trantow-Barrows                15000.0  1.333333

In [ ]:
# Pivote The DATA
# As we build up the table , I think its easiest to take it one step at a time, Add items
# one at a time and check each step to verify you are getting teh results you expect.
The simplest pivote table must have a data frame and an index

In [13]:
pd.pivot_table(df,index=["Name","Rep","Manager"],values=["Quantity","Price"],aggfunc="mean")

                                                             Price  Quantity
Name                         Rep           Manager
Barton LLC                   John Smith    Debra Henley    35000.0  1.000000
Fritsch, Russel and Anderson Craig Booker  Debra Henley    35000.0  1.000000
Herman LLC                   Cedric Moss   Fred Anderson   65000.0  2.000000
Jerde-Hilpert                John Smith    Debra Henley     5000.0  2.000000
Kassulke, Ondricka and Metz  Wendy Yule    Fred Anderson    7000.0  3.000000
Keeling LLC                  Wendy Yule    Fred Anderson  100000.0  5.000000
Kiehn-Spinka                 Daniel Hilton Debra Henley    65000.0  2.000000
Koepp Ltd                    Wendy Yule    Fred Anderson   35000.0  2.000000
Kulas Inc                    Daniel Hilton Debra Henley    25000.0  1.500000
Purdy-Kunde                  Cedric Moss   Fred Anderson   30000.0  1.000000
Stokes LLC                   Cedric Moss   Fred Anderson    7500.0  1.000000
Trantow-Barrows              Craig Booker  Debra Henley    15000.0  1.333333

In [14]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Quantity","Price"],aggfunc="sum")

                              Price  Quantity
Manager       Rep
Debra Henley  Craig Booker    80000         5
              Daniel Hilton  115000         5
              John Smith      40000         3
Fred Anderson Cedric Moss    110000         5
              Wendy Yule     177000        12

In [16]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"])

                                    Price
Manager       Rep
Debra Henley  Craig Booker   20000.000000
              Daniel Hilton  38333.333333
              John Smith     20000.000000
Fred Anderson Cedric Moss    27500.000000
              Wendy Yule     44250.000000

In [19]:
#data=df["Rep"]== "Craig Booker"

# print(data)
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],aggfunc=np.sum)

                              Price
Manager       Rep
Debra Henley  Craig Booker    80000
              Daniel Hilton  115000
              John Smith      40000
Fred Anderson Cedric Moss    110000
              Wendy Yule     177000

In [20]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"], columns=["Product"],aggfunc=np.sum)

                                Price
Product                           CPU Maintenance Monitor Software
Manager       Rep
Debra Henley  Craig Booker    65000.0      5000.0     NaN  10000.0
              Daniel Hilton  105000.0         NaN     NaN  10000.0
              John Smith      35000.0      5000.0     NaN      NaN
Fred Anderson Cedric Moss     95000.0      5000.0     NaN  10000.0
              Wendy Yule     165000.0      7000.0  5000.0      NaN

In [22]:
pd.pivot_table(df,index=["Manager","Rep","Product"],values=["Price","Quantity"],aggfunc=np.sum,fill_value=0)

                                          Price  Quantity
Manager       Rep           Product
Debra Henley  Craig Booker  CPU           65000         2
                            Maintenance    5000         2
                            Software      10000         1
              Daniel Hilton CPU          105000         4
                            Software      10000         1
              John Smith    CPU           35000         1
                            Maintenance    5000         2
Fred Anderson Cedric Moss   CPU           95000         3
                            Maintenance    5000         1
                            Software      10000         1
              Wendy Yule    CPU          165000         7
                            Maintenance    7000         3
                            Monitor        5000         2

In [ ]:
pd.pivote_table(df,index=["Manager","Rep","Product"],values=["Price","Quantity"],aggfunc

In [24]:
pd.pivot_table(df,index=["Manager","Rep","Product"],
               values=["Price","Quantity"],
               aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

                                            sum                   mean  \
                                          Price Quantity         Price
Manager       Rep           Product
Debra Henley  Craig Booker  CPU           65000        2  32500.000000
                            Maintenance    5000        2   5000.000000
                            Software      10000        1  10000.000000
              Daniel Hilton CPU          105000        4  52500.000000
                            Software      10000        1  10000.000000
              John Smith    CPU           35000        1  35000.000000
                            Maintenance    5000        2   5000.000000
Fred Anderson Cedric Moss   CPU           95000        3  47500.000000
                            Maintenance    5000        1   5000.000000
                            Software      10000        1  10000.000000
              Wendy Yule    CPU          165000        7  82500.000000
                            Maintenance    7000        3   7000.000000
                            Monitor        5000        2   5000.000000
All                                      522000       30  30705.882353


                                         Quantity
Manager       Rep           Product
Debra Henley  Craig Booker  CPU          1.000000
                            Maintenance  2.000000
                            Software     1.000000
              Daniel Hilton CPU          2.000000
                            Software     1.000000
              John Smith    CPU          1.000000
                            Maintenance  2.000000
Fred Anderson Cedric Moss   CPU          1.500000
                            Maintenance  1.000000
                            Software     1.000000
              Wendy Yule    CPU          3.500000
                            Maintenance  3.000000
                            Monitor      2.000000
All                                      1.764706

In [26]:
pd.pivot_table(df,index=["Manager","Status"],columns=["Product"],values=["Quantity","Price"],aggfunc={"Quantity":len,"Price":np.sum},fill_value=0)

                          Price                              Quantity  \
Product                     CPU Maintenance Monitor Software      CPU
Manager       Status
Debra Henley  declined    70000           0       0        0        2
              pending     40000       10000       0        0        1
              presented   30000           0       0    20000        1
              won         65000           0       0        0        1
Fred Anderson declined    65000           0       0        0        1
              pending         0        5000       0        0        0
              presented   30000           0    5000    10000        1
              won        165000        7000       0        0        2


Product                 Maintenance Monitor Software
Manager       Status
Debra Henley  declined            0       0        0
              pending             2       0        0
              presented           0       0        2
              won                 0       0        0
Fred Anderson declined            0       0        0
              pending             1       0        0
              presented           0       1        1
              won                 1       0        0

In [29]:
table=pd.pivot_table(df,index=["Manager","Status"],columns=["Product"],values=["Quantity","Price"],aggfunc={"Quantity":len,"Price":[np.sum,np.mean]},fill_value=0)
table

                           Price                                       \
                            mean                                  sum
Product                      CPU Maintenance Monitor Software     CPU
Manager       Status
Debra Henley  declined   35000.0         0.0     0.0      0.0   70000
              pending    40000.0      5000.0     0.0      0.0   40000
              presented  30000.0         0.0     0.0  10000.0   30000
              won        65000.0         0.0     0.0      0.0   65000
Fred Anderson declined   65000.0         0.0     0.0      0.0   65000
              pending        0.0      5000.0     0.0      0.0       0
              presented  30000.0         0.0  5000.0  10000.0   30000
              won        82500.0      7000.0     0.0      0.0  165000

                                                     Quantity              \
                                                          len
Product                 Maintenance Monitor Software      CPU Maintenance
Manager       Status
Debra Henley  declined            0       0        0        2           0
              pending         10000       0        0        1           2
              presented           0       0    20000        1           0
              won                 0       0        0        1           0
Fred Anderson declined            0       0        0        1           0
              pending          5000       0        0        0           1
              presented           0    5000    10000        1           0
              won              7000       0        0        2           1



Product                 Monitor Software
Manager       Status
Debra Henley  declined        0        0
              pending         0        0
              presented       0        2
              won             0        0
Fred Anderson declined        0        0
              pending         0        0
              presented       1        1
              won             0        0

In [30]:
table.query("Manager == ["Fred Anderson"]')

SyntaxError: unterminated string literal (detected at line 1) (915090531.py, line 1)