#Logistics Regression ALGO
# LR is a stastical and Machine learinging ALgorithm used for classification preoblem ,
# especially  when the outcome is binary 1,0 (Yes/No, Spam/NotSpam,)
# instead of predicting a continous value , it predict the probability that observation 
# belongs to a particular class.
# it used function that is called segmoid


# The logistic regression model uses the sigmoid Founction
# p(Y=1/X)=1/
#   (x)=Sigmoid (x) .(1-Sigmoid(x))
Study Hr      Pass / Fail(0/1) 
2             0             25%
3             0             25%
5             1             70%
7             1             90%

Threshold 
0.5

its complexity is very high


IT is basically 3 Types of LR 

1.Binay Logistic Regression
2.Multinominal Logistic Regression
3.Ordinal Logistic Regression

//Ordinal LOw Medium Hight 

// orders are (Yes / No) is called Binary Logistic Regression

---------------------l------------------------

In [22]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

In [25]:
data = pd.read_excel(r"C:/Users/ajayt/OneDrive/Desktop/DataSets/study.xlsx")

In [26]:
x=data.iloc[:,0:1]

In [27]:
y=data.iloc[:,1]

In [28]:
y.shape

(12,)

In [29]:
model=LogisticRegression()

In [31]:
model.fit(x,y)

LogisticRegression()

In [33]:
hours=[[3.5]]

In [35]:
prediction=model.predict(hours)

C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [36]:
probability=model.predict_proba(hours)

C:\Users\ajayt\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [37]:
print("Prediction:",prediction[0])
print("Probability:",probability[0][0])
print("Probability of Pass ",probability[0][1])

Prediction: 0
Probability: 0.7639023390397979
Probability of Pass  0.23609766096020218

In [38]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd

In [ ]:
C:\Users\ajayt\OneDrive\Desktop\DataSets

In [43]:
data=pd.read_csv(r'C:\Users\ajayt\OneDrive\Desktop\DataSets\spam.csv',encoding="latin1")

In [45]:
data.shape

(5572, 5)

In [48]:
data

        v1                                                 v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      ham  Go until jurong point, crazy.. Available only ...        NaN        NaN        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN        NaN        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN        NaN
3      ham  U dun say so early hor... U c already then say...        NaN        NaN        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN        NaN        NaN
...    ...                                                ...        ...        ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN        NaN        NaN
5568   ham              Will Ì_ b going to esplanade fr home?        NaN        NaN        NaN
5569   ham  Pity, * was in mood for that. So...any other s...        NaN        NaN        NaN
5570   ham  The guy did some bitching but I acted like i'd...        NaN        NaN        NaN
5571   ham                         Rofl. Its true to its name        NaN        NaN        NaN

[5572 rows x 5 columns]

In [49]:
data.head()

     v1                                                 v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0   ham  Go until jurong point, crazy.. Available only ...        NaN        NaN        NaN
1   ham                      Ok lar... Joking wif u oni...        NaN        NaN        NaN
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN        NaN
3   ham  U dun say so early hor... U c already then say...        NaN        NaN        NaN
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN        NaN        NaN

In [53]:
data.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1)

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [54]:
data.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64