In [1]:
import pandas as pd
import numpy as np

In [9]:
import os  # OS LIBRARY 
print(os.getcwd())
 
os.chdir("C:/Users/ajayt/OneDrive/Desktop/DataSets/data")

print(os.getcwd())
datalist=os.listdir()
for li in datalist:
    print(li)

C:\Users\ajayt\OneDrive\Desktop\PythonReLearn
C:\Users\ajayt\OneDrive\Desktop\DataSets\data
2018_Sales_Total.xlsx
2018_Sales_Total_Tabs.xlsx
2018_Sales_Total_v2.xlsx
81A0C300
All-Web-Site-Data-Audience-Overview.xlsx
Aussie_Wines_Plotting.csv
customer-status.xlsx
d1.xlsx
d2.xlsx
department.csv
dummy.xlsx
hospital_account_dupes.csv
hospital_account_info.csv
hospital_reimbursement.csv
March-2017-forecast-article.xlsx
mn-budget-detail-2014.csv
MN_Traffic_Fatalities.csv
sales-estimate.xlsx
sales-feb-2014.xlsx
sales-jan-2014.xlsx
sales-mar-2014.xlsx
salesfunnel.xlsx
sales_cleanup.xlsx
sales_data_types.csv
sales_transactions.xlsx
sample-address-1.xlsx
sample-address-2.xlsx
sample-sales-reps.xlsx
sample-sales-tax.csv
sample-salesv3.xlsx
Traffic_20170306-20170519.xlsx

In [10]:
import glob

In [11]:
#glob.glob('../data/*_*')#All files
glob.glob("sales-*-2014.xlsx")  #only

['sales-feb-2014.xlsx', 'sales-jan-2014.xlsx', 'sales-mar-2014.xlsx']

In [14]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
#Nmae 
all_data=pd.DataFrame()
for name in glob.glob("sales-*-2014.xlsx"):
    df = pd.read_excel(name)
    #print(name)
    all_data=pd.concat([all_data,df],ignore_index=True)
all_data=pd.DataFrame(all_data)
print(all_data.shape)
print(type(all_data))

(384, 7)
<class 'pandas.DataFrame'>

In [27]:
# all_data.to_excel(r"C:/Users/ajayt/OneDrive/Desktop/Manupulated")
all_data.to_excel(r"C:/Users/ajayt/OneDrive/Desktop/Manupulated.xlsx", index=False)

In [28]:
all_data

,account number,name,sku,quantity,unit price,ext price,date
0,383080,Will LLC,B1-20000,7,33.69,235.83,2014-02-01 09:04:59
1,412290,Jerde-Hilpert,S1-27722,11,21.12,232.32,2014-02-01 11:51:46
2,412290,Jerde-Hilpert,B1-86481,3,35.99,107.97,2014-02-01 17:24:32
3,412290,Jerde-Hilpert,B1-20000,23,78.90,1814.70,2014-02-01 19:56:48
4,672390,Kuhn-Gusikowski,S1-06532,48,55.82,2679.36,2014-02-02 03:45:20
...,...,...,...,...,...,...,...
379,737550,"Fritsch, Russel and Anderson",B1-65551,12,56.24,674.88,2014-03-31 08:43:24
380,642753,Pollich LLC,S1-93683,21,92.57,1943.97,2014-03-31 11:37:34
381,412290,Jerde-Hilpert,B1-20000,30,22.38,671.40,2014-03-31 21:41:31
382,307599,"Kassulke, Ondricka and Metz",S2-16558,46,56.04,2577.84,2014-03-31 22:11:22
383,672390,Kuhn-Gusikowski,B1-04202,19,27.86,529.34,2014-03-31 23:13:14

In [29]:
data1=pd.read_excel('sales-jan-2014.xlsx')
data2=pd.read_excel('sales-feb-2014.xlsx')
data3=pd.read_excel('sales-mar-2014.xlsx')
data=[data1,data2,data3]
data4=pd.concat(data)
print(data4.head())
print(data4.shape)

   account number                         name       sku  quantity  \
0          740150                   Barton LLC  B1-20000        39
1          714466              Trantow-Barrows  S2-77896        -1
2          218895                    Kulas Inc  B1-69924        23
3          307599  Kassulke, Ondricka and Metz  S1-65481        41
4          412290                Jerde-Hilpert  S2-34077         6

   unit price  ext price                 date
0       86.69    3380.91  2014-01-01 07:21:51
1       63.16     -63.16  2014-01-01 10:00:47
2       90.70    2086.10  2014-01-01 13:24:58
3       21.05     863.05  2014-01-01 15:05:22
4       83.21     499.26  2014-01-01 23:26:55
(384, 7)

In [30]:
all_data.describe()

       account number    quantity  unit price    ext price
count      384.000000  384.000000  384.000000   384.000000
mean    478125.989583   24.372396   56.651406  1394.517344
std     220902.947401   14.373219   27.075883  1117.809743
min     141962.000000   -1.000000   10.210000   -97.160000
25%     257198.000000   12.000000   32.612500   482.745000
50%     424914.000000   23.500000   58.160000  1098.710000
75%     714466.000000   37.000000   80.965000  2132.260000
max     786968.000000   49.000000   99.730000  4590.810000

In [31]:
all_data.max()

account number                 786968
name                         Will LLC
sku                          S2-83881
quantity                           49
unit price                      99.73
ext price                     4590.81
date              2014-03-31 23:13:14
dtype: object

In [32]:
all_data.head(10)

,account number,name,sku,quantity,unit price,ext price,date
0,383080,Will LLC,B1-20000,7,33.69,235.83,2014-02-01 09:04:59
1,412290,Jerde-Hilpert,S1-27722,11,21.12,232.32,2014-02-01 11:51:46
2,412290,Jerde-Hilpert,B1-86481,3,35.99,107.97,2014-02-01 17:24:32
3,412290,Jerde-Hilpert,B1-20000,23,78.90,1814.70,2014-02-01 19:56:48
4,672390,Kuhn-Gusikowski,S1-06532,48,55.82,2679.36,2014-02-02 03:45:20
5,383080,Will LLC,S1-82801,21,13.62,286.02,2014-02-02 12:45:50
6,714466,Trantow-Barrows,S1-06532,9,92.55,832.95,2014-02-02 17:40:58
7,239344,Stokes LLC,S1-47412,44,78.91,3472.04,2014-02-02 19:58:26
8,672390,Kuhn-Gusikowski,S1-27722,36,25.42,915.12,2014-02-03 01:28:04
9,307599,"Kassulke, Ondricka and Metz",S1-27722,32,95.66,3061.12,2014-02-03 11:27:34

In [33]:
all_data.dtypes

account number      int64
name                  str
sku                   str
quantity            int64
unit price        float64
ext price         float64
date                  str
dtype: object

In [34]:
all_data.index

RangeIndex(start=0, stop=384, step=1)

In [35]:
all_data['date']=pd.to_datetime(all_data['date'])
all_data.dtypes

account number             int64
name                         str
sku                          str
quantity                   int64
unit price               float64
ext price                float64
date              datetime64[us]
dtype: object

In [41]:
dd=pd.read_excel("C:/Users/ajayt/OneDrive/Desktop/DataSets/data/dummy.xlsx",names=["Name","Age","Salary"],header=None)

In [43]:
dd.head()

    Name   Age    Salary
0  Raman  23.0       NaN
1  Mohan   NaN       NaN
2  Sohan  34.0  565666.0
3  Rohan  21.0       NaN
4  Kapil  24.0  567777.0

In [37]:
dd.head()

   Raman    23  Unnamed: 2
0  Mohan   NaN         NaN
1  Sohan  34.0    565666.0
2  Rohan  21.0         NaN
3  Kapil  24.0    567777.0
4  Kamal  37.0    345555.0

In [39]:
dd.dropna(inplace=True)
dd.head()

   Raman    23  Unnamed: 2
1  Sohan  34.0    565666.0
3  Kapil  24.0    567777.0
4  Kamal  37.0    345555.0

In [44]:
dd=pd.read_excel("C:/Users/ajayt/OneDrive/Desktop/DataSets/data/dummy.xlsx",names=["Name","Age","Salary"],header=None)
dd.head()

    Name   Age    Salary
0  Raman  23.0       NaN
1  Mohan   NaN       NaN
2  Sohan  34.0  565666.0
3  Rohan  21.0       NaN
4  Kapil  24.0  567777.0

In [46]:
dd.dropna(thresh=2,inplace=True)
dd.head()

    Name   Age    Salary
0  Raman  23.0       NaN
2  Sohan  34.0  565666.0
3  Rohan  21.0       NaN
4  Kapil  24.0  567777.0
5  Kamal  37.0  345555.0

In [47]:
dd=pd.read_excel("C:/Users/ajayt/OneDrive/Desktop/DataSets/data/dummy.xlsx",names=["Name","Age","Salary"],header=None)
dd.head()

    Name   Age    Salary
0  Raman  23.0       NaN
1  Mohan   NaN       NaN
2  Sohan  34.0  565666.0
3  Rohan  21.0       NaN
4  Kapil  24.0  567777.0

In [48]:
import pandas as pd
status =pd.read_excel("C:/Users/ajayt/OneDrive/Desktop/DataSets/data/customer-status.xlsx")
status.shape

(16, 3)

In [49]:
all_data_st=pd.merge(all_data,status,how="left")
print(all_data_st.head(10))
print(all_data_st.shape)

   account number                         name       sku  quantity  \
0          383080                     Will LLC  B1-20000         7
1          412290                Jerde-Hilpert  S1-27722        11
2          412290                Jerde-Hilpert  B1-86481         3
3          412290                Jerde-Hilpert  B1-20000        23
4          672390              Kuhn-Gusikowski  S1-06532        48
5          383080                     Will LLC  S1-82801        21
6          714466              Trantow-Barrows  S1-06532         9
7          239344                   Stokes LLC  S1-47412        44
8          672390              Kuhn-Gusikowski  S1-27722        36
9          307599  Kassulke, Ondricka and Metz  S1-27722        32

   unit price  ext price                date  status
0       33.69     235.83 2014-02-01 09:04:59     NaN
1       21.12     232.32 2014-02-01 11:51:46  bronze
2       35.99     107.97 2014-02-01 17:24:32  bronze
3       78.90    1814.70 2014-02-01 19:56:48  bronze
4       55.82    2679.36 2014-02-02 03:45:20  silver
5       13.62     286.02 2014-02-02 12:45:50     NaN
6       92.55     832.95 2014-02-02 17:40:58  silver
7       78.91    3472.04 2014-02-02 19:58:26    gold
8       25.42     915.12 2014-02-03 01:28:04  silver
9       95.66    3061.12 2014-02-03 11:27:34  bronze
(384, 8)

In [ ]:
all_data_st["stats"]=all_data

In [ ]:
all_data_st[all_data_st['account_number']]

In [ ]:
all_data_st[all_data_st[]